on:
  push:
  pull_request_target:
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: thatdot/copybara-action@62760d38c195b5d110ebd2c6309ddc272769f885
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          access_token: ${{ secrets.GH_TOKEN }}
          sot_repo: graham33/dotfiles
          destination_repo: graham33/dotfiles-public
          destination_branch: main
          push_exclude: ".github user-config.nix hyprland.conf octaverc config/hypr config/vlc config/zoomus.conf"
          copybara_options: "--init-history"
