on:
  push:
  pull_request_target:
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: olivr/copybara-action@v1.2.3
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          access_token: ${{ secrets.GH_TOKEN }}
          sot_repo: graham33/dotfiles
          destination_repo: graham33/dotfiles-public
          push_exclude: "user-config.nix hyprland.conf octaverc config/hypr config/vlc config/zoomus.conf"
